# This image runs the dcos-cli test suite.

FROM ubuntu:15.04
MAINTAINER support@mesosphere.com

RUN apt-get update && apt-get install -y \
  make \
  openssh-client \
  git \
  sudo \
&& sudo apt-get update --fix-missing \
&& sudo apt-get install -y python-dev build-essential \
&& sudo apt-get install -y python-pip python-virtualenv \
&& pip install pip --upgrade \
&& pip install pyinstaller

ADD . /dcos-datastax
WORKDIR /dcos-datastax
RUN make clean env packages

RUN make binary
